spring.application.name=jenkins
server.port=8080
management.endpoints.web.exposure.include=health
marklogic.host=host.docker.internal
marklogic.port=8000
marklogic.user=admin
marklogic.password=admin123
marklogic.database=Documents